# Session 9: Matrices and Eigenvector problems

_Author: louise.dash@ucl.ac.uk    
Updated: 10/03/2021_

In this session we'll look at using matrices in Python, and in particular the calculation of the eigenvectors. This is something that becomes incredibly useful for solving problems in quantum mechanics, but as (most of) you haven't yet met the matrix formulation of quantum mechanics, we'll apply this only to some (nonetheless interesting) classical systems.

As usual, we'll start by importing the modules we'll need for this notebook. We'll be making some use of the numpy linalg (linear algebra) module, and so we'll give this its own alias to avoid having to type np.linalg repeatedly.

In [1]:
import numpy as np
import numpy.linalg as la

## Matrix basics


We'll start by reviewing some of the basics of matrices that you're already familiar with from Maths courses, and their corresponding Python functions. You'll already be familiar with many of these, as we've already used some of them to manipulate one-dimensional numpy arrays - and matrices are just an extension of this to two dimensions.

First off, let's create a matrix by hand-inputting the elements. We'll take this as our example matrix:
$$        \mathbf{A} = \begin{pmatrix}
      1 & 2 & 1 \\
      1 & 12 & 32.5 \\
      8 & 8 & 9 
    \end{pmatrix}
    $$

To input it, we just extend the same method as we used for one-dimensional arrays, using the np.array function. (n.b. Although there is a [np.matrix](http://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html) function, we're not going to use it. [Here is an explanation](https://docs.scipy.org/doc/numpy-1.17.0/user/numpy-for-matlab-users.html#array-or-matrix-which-should-i-use) why.)

In [2]:
# input row-wise, each row enclosed in [], elements separated by ,
A = np.array([[1, 2, 1], [1, 12, 32.5], [8, 8, 9]]) 
print(A)


[[ 1.   2.   1. ]
 [ 1.  12.  32.5]
 [ 8.   8.   9. ]]


We can use the same method as with 1d arrays to refer to parts of the matrix, for example:

In [3]:
print(A[0,0]) # row 1, column 1. Remember Python counts from zero!

1.0


The extension of this to two-dimensional matrices is fairly straightforward:

In [4]:
print(A[0,:]) # all of the first row

[1. 2. 1.]


In [5]:
print(A[:,2]) # all of the third column

[ 1.  32.5  9. ]


We can calculate, for example, the sum of the elements of the second row:

In [6]:
print(np.sum(A[1,:]))

45.5


Other basic matrix operations are more-or-less what you might guess them to be. For example, we can extract the diagonal elements of a matrix (like we did for the diagonal elements of the matrix of covariance in Session 3):

In [7]:
print(np.diag(A)) # diagonal elements of a matrix: note that this is itself an array

[ 1. 12.  9.]


The `np.diag` command can also be used to *construct* a diagonal matrix from a one-dimensional array:

In [10]:
x = np.arange(1,5) # create a 1d array
print(x)
xmatrix = np.diag(x) # use it to create diagonal matrix
print("Here is a diagonal matrix:\n", xmatrix)

[1 2 3 4]
Here is a diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


It's also possible to calculate the trace of a matrix, i.e. the sum of the diagonal elements.
$$
\mathrm{Tr}(\mathbf{A}) = \sum_i A_{ii}
$$

In [11]:
print("The trace of A is", np.trace(A)) # Trace - the sum of the diagonal elements.

print("Check that this is the same as sum of diagonal elements:", np.sum(np.diag(A)))

The trace of A is 22.0
Check that this is the same as sum of diagonal elements: 22.0


Others are sort-of-obvious when you see what they do.

In [12]:
I = np.eye(4)
 
print(I)

type(I) # Useful - this command will tell you what type of object I is (here it's a numpy array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


numpy.ndarray

### Calculating the transpose and determinant

The transpose operation of
a matrix swaps the rows with the columns. For example the transpose of matrix
$$\mathbf{H}=\left(\begin{matrix}1&2&5\\3&8&9\end{matrix}\right)$$ is
$$\mathbf{H}^{T}=\left(\begin{matrix}1&3\\2&8\\5&9\end{matrix}\right).$$

In Python this becomes:


In [13]:
H = np.array([[1,2,5],[3,8,9]]) 

print("H is\n", H)
HT = np.transpose(H)
print("The transpose of H is\n", HT)

H is
 [[1 2 5]
 [3 8 9]]
The transpose of H is
 [[1 3]
 [2 8]
 [5 9]]


The determinant of a matrix requires more calculation than just rearranging the elements of the matrix, and is the first function we'll use from the numpy.linalg module: `la.det()`

In [14]:
B = np.array([[1,2],[3,4]])
print("For the matrix B = \n", B)
print("The determinant of B is\n", la.det(B))
# you should be able to verify this result in your head!

For the matrix B = 
 [[1 2]
 [3 4]]
The determinant of B is
 -2.0000000000000004


### Calculating the inverse of a matrix

It's also useful to be able to calculate the inverse of a matrix. The inverse of the matrix $\mathbf{A}$ is the matrix $\mathbf{A^{-1}}$ such that the product between these two matrices is the identity matrix:

$$ \mathbf{A}\cdot\mathbf{A^{-1}} = \mathbf{I} $$

Be careful here - remember that the inverse of the matrix $\mathbf{A}$ is not $1/\mathbf{A}$ as there's no division operation between matrices.  Fortunately the Numpy function [linalg.inv](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html) can do this for us:

In [15]:
Binv = la.inv(B)
print("The inverse of B is\n", Binv)
print("We can check the result of multiplying the inverse with B")
print("This should give us an identity matrix:\n", np.matmul(B,Binv))


The inverse of B is
 [[-2.   1. ]
 [ 1.5 -0.5]]
We can check the result of multiplying the inverse with B
This should give us an identity matrix:
 [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


**IMPORTANT!** note that we used [np.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) to multiply the two matrices together, NOT the $*$ operator.  Check for yourself what happens if you use * instead of np.matmul.

Before we go on, here's a quick tabular summary of all the functions we just met.

<table>
<tr>
<th>Maths</th>
<th>Python</th>
</tr>
<tr>
<td>Summation , $\Sigma$</td>
<td>np.sum()</td>
</tr>
<tr>
<td>Diagonal</td>
<td>np.diag()</td>
</tr>
<tr>
<td>Trace: $\mathrm{Tr}(\mathbf{A})$</td>
<td>np.trace()</td>
</tr><tr>
<td>Identity matrix</td>
<td>np.eye()</td>
</tr>
<tr>
<td>Transpose: $\mathbf{A}^T$</td>
<td>np.transpose()</td>
</tr>
<tr>
<td>Determinant: $|A|$</td>
<td>np.linalg.det()</td>
</tr>
<tr>
<td>Inverse: $\mathbf{A}^{-1}$</td>
<td>np.linalg.inv()</td>
</tr>
<tr>
<td>Matrix multiplication: $\mathbf{A}\cdot\mathbf{B}$</td>
<td>np.matmul(A,B)</td>
</tr>
</table>

## Eigenvalues and Eigenvectors

The numpy linalg module can also calculate the eigenvalues and eigenvectors of a matrix. In physics, we are nearly always interested in calculating for matrices which are either real symmetric or Hermitian, and the corresponding linalg function is [eigh](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eigh.html) (the h is for Hermitian. If you ever need to calculate for a non-Hermitian matrix, use `eig` instead.). This function returns both the eigenvalues and eigenvectors of a matrix, in the following form:

In [18]:
AA = np.array([[1, 2], [2, 1]]) # a 2x2 symmetric matrix
print("The symmetric matrix:\n", AA)
eigval, eigvec = np.linalg.eigh(AA)
print("has eigenvalues \n", eigval)
print("and corresponding eigenvectors\n", eigvec)

The symmetric matrix:
 [[1 2]
 [2 1]]
has eigenvalues 
 [-1.  3.]
and corresponding eigenvectors
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


We can see that the eigenvalues are returned in the form of a one-dimensional array, and that the eigenvectors are returned as a matrix - each *column* of the matrix represents an eigenvector.

In [19]:
print("The first eigenvector is", eigvec[:,0], "\n with corresponding eigenvalue", eigval[0])

print("The second eigenvector is", eigvec[:,1], "\n with corresponding eigenvalue", eigval[1])

The first eigenvector is [-0.70710678  0.70710678] 
 with corresponding eigenvalue -1.0
The second eigenvector is [0.70710678 0.70710678] 
 with corresponding eigenvalue 3.0


Note also that the calculated eigenvectors are already normalized:

In [20]:
print("Elements of the eigenvector squared sum to ", np.sum(eigvec[:,0]**2))

Elements of the eigenvector squared sum to  0.9999999999999998


For a $2\times 2$ matrix like this, it's easy enough to calculate the eigenvalues and eigenvectors by hand. If you've ever tried to calculate the eigensolutions of a larger matrix by hand however, you'll appreciate how much easier it is to do computationally! The ability to solve large matrices opens up a whole new class of systems that we can solve, especially in quantum mechanics.

## Your task

* Do the quick quiz on Moodle
* Then download, read, and complete the second Jupyter notebook from Moodle, which will guide you through using matrices to solve for a one-dimensional system of beads coupled to springs.

In [22]:
B = np.array([[7,-3,1],[-5, np.sqrt(3),2],[2,4,np.pi]])
eigvalB, eigvecB = np.linalg.eigh(B)
print(eigvalB)
print(eigvecB)

[-4.05168034  5.88353689 10.04178692]
[[-0.42761796  0.33429449  0.83987504]
 [-0.73429303  0.41342594 -0.53841688]
 [ 0.52721592  0.84695111 -0.06868176]]
